PLATFORM_CTRIP = "CTRIP"

TRIGGER_MANUAL = "MANUAL"
TRIGGER_SCHEDULED = "SCHEDULED"
TRIGGER_SCAN = "SCAN"

STATUS_PENDING = "PENDING"
STATUS_RUNNING = "RUNNING"
STATUS_SUCCESS = "SUCCESS"
STATUS_FAILED = "FAILED"
STATUS_PARTIAL = "PARTIAL"
STATUS_PARTIAL_SUCCESS = "PARTIAL_SUCCESS"
STATUS_SKIPPED = "SKIPPED"

CHANNEL_PUSHPLUS = "PUSHPLUS"
CHANNEL_WEWORK = "WEWORK"
CHANNEL_NONE = "NONE"

QUERY_DIRECT = "DIRECT"
QUERY_TRANSFER = "TRANSFER"
QUERY_TRAIN_PLUS_FLIGHT = "TRAIN_PLUS_FLIGHT"
QUERY_HIDDEN_CITY = "HIDDEN_CITY"
QUERY_MIXED = "MIXED"

TRIP_ONE_WAY = "ONE_WAY"
TRIP_ROUND_TRIP = "ROUND_TRIP"

LEG_OUTBOUND = "OUTBOUND"
LEG_RETURN = "RETURN"
LEG_ROUND_TRIP_COMBO = "ROUND_TRIP_COMBO"

PRICE_ONE_WAY = "ONE_WAY_PRICE"
PRICE_ROUND_TRIP_STARTING = "ROUND_TRIP_STARTING_PRICE"
PRICE_ROUND_TRIP_TOTAL = "ROUND_TRIP_TOTAL_PRICE"
PRICE_ROUND_TRIP_RETURN_DELTA = "ROUND_TRIP_RETURN_PRICE_DELTA"
PRICE_UNKNOWN = "UNKNOWN"

COMPLETENESS_SNAPSHOT_ONLY = "SNAPSHOT_ONLY"
COMPLETENESS_OUTBOUND_ONLY = "OUTBOUND_ONLY"
COMPLETENESS_OUTBOUND_WITH_STARTING_PRICE = "OUTBOUND_WITH_STARTING_PRICE"
COMPLETENESS_FULL_ROUND_TRIP = "FULL_ROUND_TRIP"

RETURN_DETAIL_NOT_EXPANDED = "NOT_EXPANDED"
RETURN_DETAIL_EXPANDING = "EXPANDING"
RETURN_DETAIL_EXPANDED = "EXPANDED"
RETURN_DETAIL_EXPAND_FAILED = "EXPAND_FAILED"

ROUNDTRIP_DATA_OUTBOUND_ONLY = "OUTBOUND_ONLY"
ROUNDTRIP_DATA_FULL_COMBINATION = "FULL_COMBINATION"

ROUNDTRIP_EXPAND_NONE = "NONE"
ROUNDTRIP_EXPAND_LOWEST_TOP_N = "LOWEST_TOP_N"
ROUNDTRIP_EXPAND_SPECIFIC_RANKS = "SPECIFIC_RANKS"
ROUNDTRIP_EXPAND_ALL = "ALL"

RISK_LOW = "LOW"
RISK_MEDIUM = "MEDIUM"
RISK_HIGH = "HIGH"
